services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mariadb
      - redis
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception

  # BONUS #
  redis:
    build: ./requirements/bonus/redis/
    image: redis
    container_name: redis
    restart: always
    networks:
      - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/isromero/data/db_data
      # LINUX: device: /home/isromero/data/db_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/isromero/data/wordpress_data
      # LINUX: device: /home/isromero/data/wordpress_data
      o: bind
networks:
  inception:
    name: inception