version: '3'
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    # volumes:
    #   - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mariadb_root_password
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: isromero
      MARIADB_PASSWORD: mariadb_password
      ADMIN_USER: main_user
      ADMIN_PASSWORD: main_password
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    # volumes:
    #   - web_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: isromero
      WORDPRESS_DB_PASSWORD: wordpress_password
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    # volumes:
    #   - web_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
# volumes:
#   db_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/isromero/data/db_data
#       o: bind
#   web_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/isromero/data/web_data
#       o: bind
networks:
  inception:
    name: inception