version: '3'
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - web_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - web_data:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mariadb
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/isromero/data/db_data
      o: bind
  web_data:
    driver: local
    driver_opts:
      type: none
      device: /home/isromero/data/web_data
      o: bind
networks:
  inception:
    name: inception